include!("clicking_selected_message_copy_action_copies_that_message_parts/clicking_selected_message_copy_action_copies_that_message_to_click.rs");
include!("clicking_selected_message_copy_action_copies_that_message_parts/concierge_mouse_click_executes_visible_action_to_in_review_run_action.rs");
include!("clicking_selected_message_copy_action_copies_that_message_parts/in_review_open_action_opens_queued_review_task_thread_to_workspace.rs");
include!("clicking_selected_message_copy_action_copies_that_message_parts/workspace_operator_switch_updates_projection_before_daemon_echo_to_drag.rs");
