include!("clicking_repo_backed_chat_file_chip_requests_git_diff_parts/drag_selection_copies_expected_text_after_autoscroll_to_status_modal.rs");
include!("clicking_repo_backed_chat_file_chip_requests_git_diff_parts/participants_modal_mouse_wheel_scrolls_body_to_clicking_chat_image.rs");
include!("clicking_repo_backed_chat_file_chip_requests_git_diff_parts/spawned_thread_navigation_ordinary_switches.rs");
include!("clicking_repo_backed_chat_file_chip_requests_git_diff_parts/clicking_repo_backed_chat_file_chip_requests_git_diff_to_clicking_tool.rs");
include!("clicking_repo_backed_chat_file_chip_requests_git_diff_parts/closing_chat_file_preview_returns_to_conversation_to_goal_view_paused.rs");
include!("clicking_repo_backed_chat_file_chip_requests_git_diff_parts/goal_view_scroll_up_moves_off_bottom_after_mouse_overscroll_to_file.rs");
include!("clicking_repo_backed_chat_file_chip_requests_git_diff_parts/goal_composer_mission_control_preflight_renders_stable_sections.rs");
