include!("drag_selection_does_not_rebuild_full_transcript_for_every_parts/drag_selection_does_not_rebuild_full_transcript_for_every_mouse_event.rs");
include!("drag_selection_does_not_rebuild_full_transcript_for_every_parts/sidebar_mouse_click_reuses_cached_snapshot_for_spawned_history_to_thread.rs");
