include!("collaboration_mouse_clicks_select_rows_and_vote_actions_parts/goal_sidebar_tab_cycling_stays.rs");
include!("collaboration_mouse_clicks_select_rows_and_vote_actions_parts/goal_sidebar_row_selection_clamps_per_active_tab_to_goal_workspace.rs");
include!("collaboration_mouse_clicks_select_rows_and_vote_actions_parts/goal_workspace_plan_prompt_toggle_is_clickable_and_keyboard_expandable.rs");
include!("collaboration_mouse_clicks_select_rows_and_vote_actions_parts/threads_return_to_goal_banner_keeps_conversation_mouse_targets_aligned.rs");
include!("collaboration_mouse_clicks_select_rows_and_vote_actions_parts/goal_workspace_keyboard_navigation_auto_scrolls_timeline_to_chat_unpin.rs");
include!("collaboration_mouse_clicks_select_rows_and_vote_actions_parts/submit_operator_profile_answer_allows_empty_input_when_question.rs");
include!("collaboration_mouse_clicks_select_rows_and_vote_actions_parts/collaboration_mouse_clicks_select_rows_and_vote_actions_to_submit_prompt.rs");
