include!("builtin_goal_commands_support_goal_picker_and_new_goal_parts/migrate_preview_slash_command_sends_daemon_migration_preview_to_start.rs");
include!("builtin_goal_commands_support_goal_picker_and_new_goal_parts/goal_composer_opens_mission_control_preflight_with_main_agent_defaults.rs");
include!("builtin_goal_commands_support_goal_picker_and_new_goal_parts/builtin_goal_commands_support_goal_picker_and_new_goal_composer_to_retry.rs");
