include!("activating_about_tab_does_not_enter_edit_mode_to_commit_parts/whatsapp_link_device_probes_status_before_starting_link_flow.rs");
include!("activating_about_tab_does_not_enter_edit_mode_to_commit_parts/activating_openrouter_audio_tts_model_requests_audio_output_filter.rs");
include!("activating_about_tab_does_not_enter_edit_mode_to_commit_parts/activating_about_tab_does_not_enter_edit_mode_to_commit_subagent_editor.rs");
include!("activating_about_tab_does_not_enter_edit_mode_to_commit_parts/opening_weles_editor_hides_inherited_main_system_prompt_to_feat_skill.rs");
include!("activating_about_tab_does_not_enter_edit_mode_to_commit_parts/concierge_config_serializes_all_fields_to_concierge_settings_fields.rs");
